# Generated by Django 3.1.4 on 2021-01-08 09:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210107_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=tinymce.models.HTMLField(),
        ),
    ]
