# Generated by Django 3.1.4 on 2021-01-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210108_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('product', models.ImageField(upload_to='portfolio')),
                ('categories', models.ManyToManyField(blank=True, to='post.Category')),
            ],
        ),
    ]
